// professionalCategories.ts
export const professionalCategories = {
    "Technical Roles": [
      "smart_contract_developer",
      "frontend_developer",
      "full_stack_developer",
      "protocol_engineer",
      "security_engineer",
      "zkproof_engineer",
      "research_engineer",
      "infrastructure_engineer",
      "technical_writer",
    ],
    "Product & Design": [
      "product_manager",
      "product_designer",
      "ux_researcher",
      "technical_product_manager",
    ],
    "Business & Operations": [
      "founder",
      "business_development",
      "operations_manager",
      "treasury_manager",
      "tokenomics_designer",
      "community_manager",
      "developer_relations",
      "growth_manager",
      "partnership_manager",
    ],
    "Content & Marketing": [
      "content_creator",
      "technical_content_writer",
      "community_content_manager",
      "social_media_manager",
      "marketing_manager",
      "brand_manager",
    ],
    "Investment & Advisory": [
      "venture_capitalist",
      "angel_investor",
      "protocol_researcher",
      "tokenomics_advisor",
      "governance_specialist",
      "mev_researcher",
      "defi_strategist",
    ],
    "Trading & Analytics": [
      "quant_trader",
      "onchain_analyst",
      "data_scientist",
      "market_maker",
      "trading_strategy_developer",
    ],
  } as const;